/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;

/**
 *
 * @author Gary
 */
public class CurrentSummary1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form CurrentSummary
     */
    public CurrentSummary1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelNumberCustomers = new javax.swing.JLabel();
        textNumberCustomers = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomers = new javax.swing.JList();
        labelListOfCustomers = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        labelCashBalances = new javax.swing.JLabel();
        textCashBalances = new javax.swing.JTextField();
        labelListOfStocks = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        labelStockQuerry = new javax.swing.JLabel();
        textStockQuerry = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        labelListOfResults = new javax.swing.JLabel();
        buttonToMainMenu = new javax.swing.JButton();
        buttonCustomerPortfolio = new javax.swing.JButton();

        setTitle("Current Summary");

        labelNumberCustomers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumberCustomers.setText("Number of Customers");

        textNumberCustomers.setText("#");

        listCustomers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCustomers);

        labelListOfCustomers.setText("List of Customers");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        labelCashBalances.setText("Total of Cash Balances");

        textCashBalances.setText("$");
        textCashBalances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCashBalancesActionPerformed(evt);
            }
        });

        labelListOfStocks.setText("List of Stocks");

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        labelStockQuerry.setText("Stock Querry");

        textStockQuerry.setText("Stock Symbol");

        buttonSearch.setText("Search");

        labelListOfResults.setText("List of Customers With Stock");

        buttonToMainMenu.setText("Main Menu");
        buttonToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToMainMenuActionPerformed(evt);
            }
        });

        buttonCustomerPortfolio.setText("Customer Portfolio");
        buttonCustomerPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerPortfolioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(labelNumberCustomers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNumberCustomers, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelListOfCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCashBalances, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(textCashBalances)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonCustomerPortfolio)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(labelListOfStocks, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonToMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(labelStockQuerry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textStockQuerry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSearch))
                    .addComponent(labelListOfResults, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberCustomers)
                    .addComponent(labelCashBalances)
                    .addComponent(labelStockQuerry))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNumberCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCashBalances, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStockQuerry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelListOfCustomers)
                    .addComponent(labelListOfStocks)
                    .addComponent(labelListOfResults))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonToMainMenu)
                    .addComponent(buttonCustomerPortfolio))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCashBalancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCashBalancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCashBalancesActionPerformed

    private void buttonToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToMainMenuActionPerformed
        cl.show(homeContainer, "Main Menu");
    }//GEN-LAST:event_buttonToMainMenuActionPerformed

    private void buttonCustomerPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerPortfolioActionPerformed
        cl.show(homeContainer, "Customer Portfolio");
    }//GEN-LAST:event_buttonCustomerPortfolioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCustomerPortfolio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonToMainMenu;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCashBalances;
    private javax.swing.JLabel labelListOfCustomers;
    private javax.swing.JLabel labelListOfResults;
    private javax.swing.JLabel labelListOfStocks;
    private javax.swing.JLabel labelNumberCustomers;
    private javax.swing.JLabel labelStockQuerry;
    private javax.swing.JList listCustomers;
    private javax.swing.JTextField textCashBalances;
    private javax.swing.JTextField textNumberCustomers;
    private javax.swing.JTextField textStockQuerry;
    // End of variables declaration//GEN-END:variables
}
