/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;
import static stockbroker9.Driver.client;

/**
 *
 * @author Gary
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonMonthlyReports = new javax.swing.JButton();
        buttonCurrentSummary1 = new javax.swing.JButton();
        buttonLogin1 = new javax.swing.JButton();
        buttonCustomerPortfolio = new javax.swing.JButton();
        buttonAdministrator = new javax.swing.JButton();
        buttonSetCommissionRate = new javax.swing.JButton();
        buttonSalesActivity = new javax.swing.JButton();
        buttonImportCustomerData = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        buttonMonthlyReports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMonthlyReports.setText("Monthly Reports");
        buttonMonthlyReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonthlyReportsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 65, 0, 52);
        add(buttonMonthlyReports, gridBagConstraints);

        buttonCurrentSummary1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCurrentSummary1.setText("Current Summary");
        buttonCurrentSummary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCurrentSummary1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 100, 0, 0);
        add(buttonCurrentSummary1, gridBagConstraints);

        buttonLogin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLogin1.setText("Login");
        buttonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogin1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 65, 0, 52);
        add(buttonLogin1, gridBagConstraints);

        buttonCustomerPortfolio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCustomerPortfolio.setText("Customer Portfolio");
        buttonCustomerPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerPortfolioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 100, 0, 0);
        add(buttonCustomerPortfolio, gridBagConstraints);

        buttonAdministrator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAdministrator.setText("Administrator");
        buttonAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdministratorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 65, 0, 52);
        add(buttonAdministrator, gridBagConstraints);

        buttonSetCommissionRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSetCommissionRate.setText("Set Commission Rate");
        buttonSetCommissionRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetCommissionRateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 100, 0, 0);
        add(buttonSetCommissionRate, gridBagConstraints);

        buttonSalesActivity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSalesActivity.setText("Sales Activity");
        buttonSalesActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalesActivityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(90, 65, 0, 52);
        add(buttonSalesActivity, gridBagConstraints);

        buttonImportCustomerData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonImportCustomerData.setText("Import Customer Data");
        buttonImportCustomerData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportCustomerDataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 100, 0, 0);
        add(buttonImportCustomerData, gridBagConstraints);

        buttonExit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 148;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 65, 124, 52);
        add(buttonExit, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMonthlyReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonthlyReportsActionPerformed
        cl.show(homeContainer, "Monthly Reports");
    }//GEN-LAST:event_buttonMonthlyReportsActionPerformed

    private void buttonCurrentSummary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCurrentSummary1ActionPerformed
        cl.show(homeContainer, "Current Summary");
    }//GEN-LAST:event_buttonCurrentSummary1ActionPerformed

    private void buttonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogin1ActionPerformed
        cl.show(homeContainer, "Login");
    }//GEN-LAST:event_buttonLogin1ActionPerformed

    private void buttonCustomerPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerPortfolioActionPerformed
        cl.show(homeContainer, "Customer Portfolio");
    }//GEN-LAST:event_buttonCustomerPortfolioActionPerformed

    private void buttonAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdministratorActionPerformed
        cl.show(homeContainer, "Administrator");
    }//GEN-LAST:event_buttonAdministratorActionPerformed

    private void buttonSetCommissionRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetCommissionRateActionPerformed
        cl.show(homeContainer, "Set Commission Rate");
    }//GEN-LAST:event_buttonSetCommissionRateActionPerformed

    private void buttonSalesActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalesActivityActionPerformed
        cl.show(homeContainer, "Sales Activity");
    }//GEN-LAST:event_buttonSalesActivityActionPerformed

    private void buttonImportCustomerDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportCustomerDataActionPerformed
        cl.show(homeContainer, "Import Customer Data");
    }//GEN-LAST:event_buttonImportCustomerDataActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        System.exit(1);
    }//GEN-LAST:event_buttonExitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdministrator;
    private javax.swing.JButton buttonCurrentSummary1;
    private javax.swing.JButton buttonCustomerPortfolio;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonImportCustomerData;
    private javax.swing.JButton buttonLogin1;
    private javax.swing.JButton buttonMonthlyReports;
    private javax.swing.JButton buttonSalesActivity;
    private javax.swing.JButton buttonSetCommissionRate;
    // End of variables declaration//GEN-END:variables
}
