/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;

/**
 *
 * @author Gary
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonMonthlyReports = new javax.swing.JButton();
        buttonCurrentSummary1 = new javax.swing.JButton();
        buttonLogin1 = new javax.swing.JButton();
        buttonCustomerPortfolio = new javax.swing.JButton();
        buttonAdministrator = new javax.swing.JButton();
        buttonSetCommissionRate = new javax.swing.JButton();
        buttonSalesActivity = new javax.swing.JButton();
        buttonImportCustomerData = new javax.swing.JButton();

        buttonMonthlyReports.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonMonthlyReports.setText("Monthly Reports");
        buttonMonthlyReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMonthlyReportsActionPerformed(evt);
            }
        });

        buttonCurrentSummary1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCurrentSummary1.setText("Current Summary");
        buttonCurrentSummary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCurrentSummary1ActionPerformed(evt);
            }
        });

        buttonLogin1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonLogin1.setText("Login");
        buttonLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogin1ActionPerformed(evt);
            }
        });

        buttonCustomerPortfolio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCustomerPortfolio.setText("Customer Portfolio");
        buttonCustomerPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerPortfolioActionPerformed(evt);
            }
        });

        buttonAdministrator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonAdministrator.setText("Administrator");
        buttonAdministrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdministratorActionPerformed(evt);
            }
        });

        buttonSetCommissionRate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSetCommissionRate.setText("Set Commission Rate");
        buttonSetCommissionRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSetCommissionRateActionPerformed(evt);
            }
        });

        buttonSalesActivity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonSalesActivity.setText("Sales Activity");
        buttonSalesActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalesActivityActionPerformed(evt);
            }
        });

        buttonImportCustomerData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonImportCustomerData.setText("Import Customer Data");
        buttonImportCustomerData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImportCustomerDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonImportCustomerData)
                    .addComponent(buttonSetCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCurrentSummary1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCustomerPortfolio, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonMonthlyReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSalesActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buttonAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCustomerPortfolio)
                    .addComponent(buttonSalesActivity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCurrentSummary1)
                    .addComponent(buttonMonthlyReports))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonImportCustomerData)
                    .addComponent(buttonAdministrator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogin1)
                    .addComponent(buttonSetCommissionRate))
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMonthlyReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMonthlyReportsActionPerformed
        cl.show(homeContainer, "Monthly Reports");
    }//GEN-LAST:event_buttonMonthlyReportsActionPerformed

    private void buttonCurrentSummary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCurrentSummary1ActionPerformed
        cl.show(homeContainer, "Current Summary");
    }//GEN-LAST:event_buttonCurrentSummary1ActionPerformed

    private void buttonLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogin1ActionPerformed
        cl.show(homeContainer, "Login");
    }//GEN-LAST:event_buttonLogin1ActionPerformed

    private void buttonCustomerPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerPortfolioActionPerformed
        cl.show(homeContainer, "Customer Portfolio");
    }//GEN-LAST:event_buttonCustomerPortfolioActionPerformed

    private void buttonAdministratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdministratorActionPerformed
        cl.show(homeContainer, "Administrator");
    }//GEN-LAST:event_buttonAdministratorActionPerformed

    private void buttonSetCommissionRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetCommissionRateActionPerformed
        cl.show(homeContainer, "Set Commission Rate");
    }//GEN-LAST:event_buttonSetCommissionRateActionPerformed

    private void buttonSalesActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalesActivityActionPerformed
        cl.show(homeContainer, "Sales Activity");
    }//GEN-LAST:event_buttonSalesActivityActionPerformed

    private void buttonImportCustomerDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImportCustomerDataActionPerformed
        cl.show(homeContainer, "Import Customer Data");
    }//GEN-LAST:event_buttonImportCustomerDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdministrator;
    private javax.swing.JButton buttonCurrentSummary1;
    private javax.swing.JButton buttonCustomerPortfolio;
    private javax.swing.JButton buttonImportCustomerData;
    private javax.swing.JButton buttonLogin1;
    private javax.swing.JButton buttonMonthlyReports;
    private javax.swing.JButton buttonSalesActivity;
    private javax.swing.JButton buttonSetCommissionRate;
    // End of variables declaration//GEN-END:variables
}
