/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import java.awt.Color;
import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;
import static stockbroker9.Driver.client;

/**
 *
 * @author Gary
 */
public class Administrator extends javax.swing.JPanel {

    /**
     * Creates new form Administrator
     */
    public Administrator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jCheckBox2 = new javax.swing.JCheckBox();
        buttonMainMenu = new javax.swing.JButton();
        labelAdministrator = new javax.swing.JLabel();
        comboBoxBrokers = new javax.swing.JComboBox();
        checkBoxBroker = new javax.swing.JCheckBox();
        checkBoxAdministrator = new javax.swing.JCheckBox();
        labelBrokers = new javax.swing.JLabel();
        labelPriviledges = new javax.swing.JLabel();
        labelAddBroker = new javax.swing.JLabel();
        textEnterName = new javax.swing.JTextField();
        labelEnterName = new javax.swing.JLabel();
        passwordOne = new javax.swing.JPasswordField();
        passwordTwo = new javax.swing.JPasswordField();
        buttonEnterNewBroker = new javax.swing.JButton();
        labelEnterPassword = new javax.swing.JLabel();
        buttonRemoveBroker = new javax.swing.JButton();

        jCheckBox2.setText("jCheckBox2");

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new java.awt.GridBagLayout());

        buttonMainMenu.setText("Main Menu");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 120, 94, 0);
        add(buttonMainMenu, gridBagConstraints);

        labelAdministrator.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        labelAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAdministrator.setText("Administrator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 292;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 180, 0, 0);
        add(labelAdministrator, gridBagConstraints);

        comboBoxBrokers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 66;
        gridBagConstraints.ipady = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 180, 0, 0);
        add(comboBoxBrokers, gridBagConstraints);

        checkBoxBroker.setText("Broker");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 120, 0, 0);
        add(checkBoxBroker, gridBagConstraints);

        checkBoxAdministrator.setText("Administrator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 120, 0, 0);
        add(checkBoxAdministrator, gridBagConstraints);

        labelBrokers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBrokers.setText("Brokers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 87;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 180, 0, 0);
        add(labelBrokers, gridBagConstraints);

        labelPriviledges.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPriviledges.setText("Priviledges");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 51;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 120, 0, 0);
        add(labelPriviledges, gridBagConstraints);

        labelAddBroker.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAddBroker.setText("Add Broker");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 80, 0, 319);
        add(labelAddBroker, gridBagConstraints);

        textEnterName.setForeground(new java.awt.Color(153, 153, 153));
        textEnterName.setText("name");
        textEnterName.setPreferredSize(new java.awt.Dimension(40, 22));
        textEnterName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textEnterNameMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 80, 0, 319);
        add(textEnterName, gridBagConstraints);

        labelEnterName.setText("Enter Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 76;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 80, 0, 319);
        add(labelEnterName, gridBagConstraints);

        passwordOne.setText("jPasswordField1");
        passwordOne.setPreferredSize(new java.awt.Dimension(40, 22));
        passwordOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordOneMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 80, 0, 319);
        add(passwordOne, gridBagConstraints);

        passwordTwo.setText("jPasswordField2");
        passwordTwo.setPreferredSize(new java.awt.Dimension(40, 22));
        passwordTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTwoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 80, 0, 319);
        add(passwordTwo, gridBagConstraints);

        buttonEnterNewBroker.setText("Enter New Broker");
        buttonEnterNewBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterNewBrokerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 80, 94, 319);
        add(buttonEnterNewBroker, gridBagConstraints);

        labelEnterPassword.setText("Enter Password Twice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 80, 0, 319);
        add(labelEnterPassword, gridBagConstraints);

        buttonRemoveBroker.setText("Remove Broker");
        buttonRemoveBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveBrokerActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 180, 94, 0);
        add(buttonRemoveBroker, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        cl.show(homeContainer, "Main Menu");
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    private void buttonRemoveBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveBrokerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRemoveBrokerActionPerformed

    private void textEnterNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textEnterNameMouseClicked
        textEnterName.setText("");
        textEnterName.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_textEnterNameMouseClicked

    private void passwordOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordOneMouseClicked
        passwordOne.setText("");
    }//GEN-LAST:event_passwordOneMouseClicked

    private void passwordTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTwoMouseClicked
        passwordTwo.setText(""); // TODO add your handling code here:
    }//GEN-LAST:event_passwordTwoMouseClicked

    private void buttonEnterNewBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnterNewBrokerActionPerformed
        if(!(passwordOne.getPassword()==passwordTwo.getPassword())){
            labelEnterPassword.setText("Passwords do not match. Try again.");
        }else{
           labelEnterPassword.setText("Enter Password Twice"); 
        }
    }//GEN-LAST:event_buttonEnterNewBrokerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnterNewBroker;
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JButton buttonRemoveBroker;
    private javax.swing.JCheckBox checkBoxAdministrator;
    private javax.swing.JCheckBox checkBoxBroker;
    private javax.swing.JComboBox comboBoxBrokers;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel labelAddBroker;
    private javax.swing.JLabel labelAdministrator;
    private javax.swing.JLabel labelBrokers;
    private javax.swing.JLabel labelEnterName;
    private javax.swing.JLabel labelEnterPassword;
    private javax.swing.JLabel labelPriviledges;
    private javax.swing.JPasswordField passwordOne;
    private javax.swing.JPasswordField passwordTwo;
    private javax.swing.JTextField textEnterName;
    // End of variables declaration//GEN-END:variables
}
