/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import java.awt.Color;
import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;
import static stockbroker9.Driver.client;
import java.io.File;
import java.io.FileNotFoundException;
/**
 *
 * @author Gary, Matthew (List of customers)
 */
public class CurrentSummary1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form CurrentSummary
     */
    public CurrentSummary1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelNumberCustomers = new javax.swing.JLabel();
        textNumberCustomers = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCustomers = new javax.swing.JList();
        labelListOfCustomers = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        labelCashBalances = new javax.swing.JLabel();
        textCashBalances = new javax.swing.JTextField();
        labelListOfStocks = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        labelStockQuerry = new javax.swing.JLabel();
        textStockQuerry = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        labelListOfResults = new javax.swing.JLabel();
        buttonToMainMenu = new javax.swing.JButton();
        buttonCustomerPortfolio = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));
        setTitle("Current Summary");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        labelNumberCustomers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNumberCustomers.setText("Number of Customers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 100, 0, 0);
        getContentPane().add(labelNumberCustomers, gridBagConstraints);

        textNumberCustomers.setEditable(false);
        textNumberCustomers.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 100, 0, 0);
        getContentPane().add(textNumberCustomers, gridBagConstraints);

        listCustomers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Victoria North", "Michael Perry", "Ivan Gregory", "Jayne Duquette", "William Cooper Sn.",
                                 "Gabriel Shumaker", "Justin Herrington", "Matthew Herrin", "Bryce McDaniels", "Andrew Martin"};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCustomers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 100, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        labelListOfCustomers.setText("List of Customers");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 100, 0, 0);
        getContentPane().add(labelListOfCustomers, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {"AAPL", "GOOG", "V", "T", "WMAR",
                    "HAS", "TSO" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 122;
        gridBagConstraints.ipady = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 114, 0, 0);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        labelCashBalances.setText("Total of Cash Balances");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 114, 0, 0);
        getContentPane().add(labelCashBalances, gridBagConstraints);

        textCashBalances.setEditable(false);
        textCashBalances.setText("$");
        textCashBalances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCashBalancesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 143;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 114, 0, 0);
        getContentPane().add(textCashBalances, gridBagConstraints);

        labelListOfStocks.setText("List of Stocks");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 74;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 114, 0, 0);
        getContentPane().add(labelListOfStocks, gridBagConstraints);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Victoria North", "Gabriel Shumaker", "Matthew Herrin", "William Cooper Sn.", "Andrew Martin"};


            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 151;
        gridBagConstraints.ipady = 166;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(21, 90, 0, 100);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        labelStockQuerry.setText("Stock Querry");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 104;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 90, 0, 100);
        getContentPane().add(labelStockQuerry, gridBagConstraints);

        textStockQuerry.setForeground(new java.awt.Color(153, 153, 153));
        textStockQuerry.setText("Stock Symbol");
        textStockQuerry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textStockQuerryFocusGained(evt);
            }
        });
        textStockQuerry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textStockQuerryMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 90, 0, 0);
        getContentPane().add(textStockQuerry, gridBagConstraints);

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 22, 0, 100);
        getContentPane().add(buttonSearch, gridBagConstraints);

        labelListOfResults.setText("List of Customers With Stock");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 90, 0, 100);
        getContentPane().add(labelListOfResults, gridBagConstraints);

        buttonToMainMenu.setText("Main Menu");
        buttonToMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonToMainMenuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 83;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 90, 179, 100);
        getContentPane().add(buttonToMainMenu, gridBagConstraints);

        buttonCustomerPortfolio.setText("Customer Portfolio");
        buttonCustomerPortfolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomerPortfolioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(37, 114, 179, 0);
        getContentPane().add(buttonCustomerPortfolio, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCashBalancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCashBalancesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCashBalancesActionPerformed

    private void buttonToMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonToMainMenuActionPerformed
        cl.show(homeContainer, "Main Menu");
    }//GEN-LAST:event_buttonToMainMenuActionPerformed

    private void buttonCustomerPortfolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCustomerPortfolioActionPerformed
        cl.show(homeContainer, "Customer Portfolio");
    }//GEN-LAST:event_buttonCustomerPortfolioActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void textStockQuerryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textStockQuerryMouseClicked
        textStockQuerry.setText("");
        textStockQuerry.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_textStockQuerryMouseClicked

    private void textStockQuerryFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textStockQuerryFocusGained
        textStockQuerry.setText("");
        textStockQuerry.setForeground(Color.black);      // TODO add your handling code here:
    }//GEN-LAST:event_textStockQuerryFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCustomerPortfolio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonToMainMenu;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelCashBalances;
    private javax.swing.JLabel labelListOfCustomers;
    private javax.swing.JLabel labelListOfResults;
    private javax.swing.JLabel labelListOfStocks;
    private javax.swing.JLabel labelNumberCustomers;
    private javax.swing.JLabel labelStockQuerry;
    private javax.swing.JList listCustomers;
    private javax.swing.JTextField textCashBalances;
    private javax.swing.JTextField textNumberCustomers;
    private javax.swing.JTextField textStockQuerry;
    // End of variables declaration//GEN-END:variables
}
