/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockbroker9;

import java.awt.Color;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import static stockbroker9.Driver.cl;
import static stockbroker9.Driver.homeContainer;
import static stockbroker9.Driver.client;
import java.io.File;
import java.io.FileNotFoundException;

/**
 *
 * @author Gary
 */
public class CustomerPortfolio extends javax.swing.JInternalFrame implements Observer {

    DecimalFormat moneyFormat;

    double testMoney = 10000;//remove after testing

    public void setConfirmEnabled(boolean confirmStatus) {
        buttonConfirm.setEnabled(confirmStatus);
    }

    public void setBalance() {
        textCash.setText(moneyFormat.format(testMoney));
    }

    public void openFile() {

    }


    @Override
    public void update(Observable obj, Object arg) {
        //refreshComponents();
        System.out.println("test point 10 Observer notified");
        textCommissionRate.setText(Double.toString(client.getCommissionRate()));
        //textCommissionRate.setText("Happy rate");
    }

    /**
     * Creates new form CustomerPortfolio
     */
    public CustomerPortfolio() {
        this.moneyFormat = new DecimalFormat("$#,###,##0.00");
        initComponents();
    }

    public void refreshComponents() {
        textCommissionRate.setText(Double.toString(client.getCommissionRate()));
    }

    public short toShort(String input) {
        input = input.trim();
        short output = Short.parseShort(input);
        return output;
    }

    public double toDouble(String input) {
        input = input.trim();
        double output = Double.parseDouble(input);
        return output;
    }

    public String getTotalValue() {
        String output = Double.toString(toDouble(textMarketPrice.getText()) * toDouble(textQuantity.getText()));
        return output;
    }

    public void refreshStatusLabel() {
        labelStatus.setVisible(false);
        labelStatus.setText(" ");
    }

    public double calculateValue() {
        return (Double.parseDouble(textQuantity.getText()) * Double.parseDouble(textMarketPrice.getText()));
    }

    public double calculateTotalBuyValue() {
        return ((calculateValue() * Double.parseDouble(textCommissionRate.getText()) + calculateValue()));
    }

    public double calculateTotalSellValue() {
        return calculateValue() - (calculateValue() * Double.parseDouble(textCommissionRate.getText()));
    }

    private String getQuote() {
        String price = "";
        System.out.println("test point 1");
        try {
            textAreaOneYearHistory.setText("");
            String stockSymbol = textStock.getText();
            String html = ("http://finance.yahoo.com/q?s=" + stockSymbol);
            Document doc = Jsoup.connect(html).get();
            price = doc.select(".time_rtq_ticker").first().text();
            textAreaOneYearHistory.setText("The current market price for " + stockSymbol + " is $" + price);
            System.out.println(price);
        } catch (IOException ex) {
            Logger.getLogger(CustomerPortfolio.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("test point 2");
        return price;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        labelCustomerInfo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelCustomerID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        textCustomerID = new javax.swing.JTextField();
        textFirstName = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        textLastName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        textZip = new javax.swing.JTextField();
        labelAddress = new javax.swing.JLabel();
        labelCity = new javax.swing.JLabel();
        textCity = new javax.swing.JTextField();
        textState = new javax.swing.JTextField();
        labelPhone = new javax.swing.JLabel();
        textStreet = new javax.swing.JTextField();
        labelStreet = new javax.swing.JLabel();
        labelZip = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textPhone = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        textStockHeld = new javax.swing.JTextField();
        buttonLookUpPrice = new javax.swing.JButton();
        textStock = new javax.swing.JTextField();
        labelCash = new javax.swing.JLabel();
        labelAverageBasis = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        textAverageBasis = new javax.swing.JTextField();
        textCash = new javax.swing.JTextField();
        textMarketPrice = new javax.swing.JTextField();
        labelMarketPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelStockHeld = new javax.swing.JLabel();
        labelOneYearHistory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOneYearHistory = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        buttonConfirm = new javax.swing.JButton();
        radioButtonSell = new javax.swing.JRadioButton();
        labelTransactionQuantity = new javax.swing.JLabel();
        radioButtonBuy = new javax.swing.JRadioButton();
        labelTotalValue = new javax.swing.JLabel();
        labelCommissionRate = new javax.swing.JLabel();
        radioButtonAcceptDeposit = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        textQuantity = new javax.swing.JTextField();
        radioButtonDisperseFunds = new javax.swing.JRadioButton();
        textCommissionRate = new javax.swing.JTextField();
        buttonMainMenu = new javax.swing.JButton();
        labelValue = new javax.swing.JLabel();
        buttonCaluculate = new javax.swing.JButton();
        labelStatus = new javax.swing.JLabel();
        textCashDispersal = new javax.swing.JTextField();
        textCashDeposit = new javax.swing.JTextField();
        textValue = new javax.swing.JTextField();
        textTotalValue = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setTitle("Customer Portfolio");
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        labelCustomerInfo.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        labelCustomerInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCustomerInfo.setText("Customer Information");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        labelCustomerID.setText("Customer ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter either First and Last Name or Customer ID to search");

        labelFirstName.setText("First Name");

        labelLastName.setText("Last Name");

        textCustomerID.setForeground(new java.awt.Color(153, 153, 153));
        textCustomerID.setText("Customer ID");
        textCustomerID.setToolTipText("Enter Customer ID");
        textCustomerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textCustomerIDFocusGained(evt);
            }
        });
        textCustomerID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCustomerIDMouseClicked(evt);
            }
        });
        textCustomerID.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textCustomerIDInputMethodTextChanged(evt);
            }
        });

        textFirstName.setForeground(new java.awt.Color(153, 153, 153));
        textFirstName.setText("First Name");
        textFirstName.setToolTipText("Enter customer first name");
        textFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFirstNameFocusGained(evt);
            }
        });
        textFirstName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFirstNameMouseClicked(evt);
            }
        });
        textFirstName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textFirstNameInputMethodTextChanged(evt);
            }
        });

        buttonSearch.setText("Search");

        textLastName.setForeground(new java.awt.Color(153, 153, 153));
        textLastName.setText("Last Name");
        textLastName.setToolTipText("Enter customer last name");
        textLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textLastNameFocusGained(evt);
            }
        });
        textLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textLastNameMouseClicked(evt);
            }
        });
        textLastName.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textLastNameInputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(labelCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(textCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(buttonSearch))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        textZip.setEditable(false);
        textZip.setText("Zip");

        labelAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelAddress.setText("Address");

        labelCity.setText("City");

        textCity.setEditable(false);
        textCity.setText("City");

        textState.setEditable(false);
        textState.setText("State");

        labelPhone.setText("Phone");

        textStreet.setEditable(false);
        textStreet.setText("Street");

        labelStreet.setText("Street");

        labelZip.setText("Zip");

        jLabel2.setText("State");

        textPhone.setEditable(false);
        textPhone.setText("XXXXXXXXXX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(labelZip, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(textState, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(textZip, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelPhone)
                    .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelAddress)
                .addGap(7, 7, 7)
                .addComponent(labelStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(textStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCity, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZip, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(textPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(labelCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(labelCustomerInfo)
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        textStockHeld.setEditable(false);
        textStockHeld.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textStockHeld.setText("10");
        textStockHeld.setToolTipText("Shows the number of stocks held by the customer");

        buttonLookUpPrice.setText("Look Up Price");
        buttonLookUpPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLookUpPriceActionPerformed(evt);
            }
        });

        textStock.setForeground(new java.awt.Color(153, 153, 153));
        textStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textStock.setText("msft");
        textStock.setToolTipText("Enter the stock symbol to lookup");
        textStock.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textStockFocusGained(evt);
            }
        });
        textStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textStockMouseClicked(evt);
            }
        });
        textStock.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textStockInputMethodTextChanged(evt);
            }
        });

        labelCash.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelCash.setText("Cash Balance");

        labelAverageBasis.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelAverageBasis.setText("Average Basis");

        labelStock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelStock.setText("Stock");

        textAverageBasis.setEditable(false);
        textAverageBasis.setBackground(new java.awt.Color(255, 255, 255));
        textAverageBasis.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textAverageBasis.setText("22.00");
        textAverageBasis.setToolTipText("Shows the average value of the selected stock");

        textCash.setEditable(false);
        textCash.setBackground(new java.awt.Color(255, 255, 255));
        textCash.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textCash.setText(moneyFormat.format(testMoney)
        );
        textCash.setToolTipText("Shows the customers cash balance on hand in the brokerage");

        textMarketPrice.setEditable(false);
        textMarketPrice.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textMarketPrice.setText(getQuote());
        textMarketPrice.setToolTipText("Shows the current Market Price of selected stock");

        labelMarketPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelMarketPrice.setText("Market Price");

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Account Information");

        labelStockHeld.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labelStockHeld.setText("Stock Held");

        labelOneYearHistory.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        labelOneYearHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOneYearHistory.setText("One Year History");

        textAreaOneYearHistory.setEditable(false);
        textAreaOneYearHistory.setColumns(20);
        textAreaOneYearHistory.setRows(5);
        jScrollPane1.setViewportView(textAreaOneYearHistory);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelCash, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(textCash, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(labelStock, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelMarketPrice)
                .addGap(48, 48, 48)
                .addComponent(textMarketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(buttonLookUpPrice))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(labelStockHeld, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(textStockHeld, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(labelAverageBasis, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(textAverageBasis, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(labelOneYearHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelCash))
                    .addComponent(textCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelStock))
                    .addComponent(textStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelMarketPrice))
                    .addComponent(textMarketPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(buttonLookUpPrice)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelStockHeld))
                    .addComponent(textStockHeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelAverageBasis))
                    .addComponent(textAverageBasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(labelOneYearHistory)
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        buttonConfirm.setText("Confirm");
        buttonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirmActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButtonSell);
        radioButtonSell.setText("Sell");
        radioButtonSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonSellActionPerformed(evt);
            }
        });

        labelTransactionQuantity.setText("Transaction Quantity");

        buttonGroup1.add(radioButtonBuy);
        radioButtonBuy.setText("Buy");
        radioButtonBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonBuyActionPerformed(evt);
            }
        });

        labelTotalValue.setText("Total Value");

        labelCommissionRate.setText("Commission Rate");

        buttonGroup1.add(radioButtonAcceptDeposit);
        radioButtonAcceptDeposit.setText("Accept Deposit");
        radioButtonAcceptDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAcceptDepositActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Transaction");

        textQuantity.setForeground(new java.awt.Color(153, 153, 153));
        textQuantity.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textQuantity.setText("5");
        textQuantity.setToolTipText("Enter the number of stock to buy or sell");
        textQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textQuantityFocusGained(evt);
            }
        });
        textQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textQuantityMouseClicked(evt);
            }
        });

        buttonGroup1.add(radioButtonDisperseFunds);
        radioButtonDisperseFunds.setText("Disperse Funds");
        radioButtonDisperseFunds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonDisperseFundsActionPerformed(evt);
            }
        });

        textCommissionRate.setEditable(false);
        textCommissionRate.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        textCommissionRate.setText(Double.toString(client.getCommissionRate()));
        textCommissionRate.setToolTipText("Shows the current commission rate charged by the brokerage");
        textCommissionRate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                textCommissionRateInputMethodTextChanged(evt);
            }
        });
        textCommissionRate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCommissionRateActionPerformed(evt);
            }
        });

        buttonMainMenu.setText("Main Menu");
        buttonMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainMenuActionPerformed(evt);
            }
        });

        labelValue.setText("Value");

        buttonCaluculate.setText("Calculate");
        buttonCaluculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCaluculateActionPerformed(evt);
            }
        });

        labelStatus.setBackground(new java.awt.Color(51, 255, 255));
        labelStatus.setForeground(new java.awt.Color(255, 0, 51));
        labelStatus.setVisible(false);
        labelStatus.setText("Status");

        textCashDispersal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        textCashDeposit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        textValue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        textTotalValue.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCaluculate)
                            .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonAcceptDeposit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonBuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonDisperseFunds, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTransactionQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelValue)
                            .addComponent(labelCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(textTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textValue, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(textCashDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(textCashDispersal)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textCashDeposit, textCashDispersal, textCommissionRate, textQuantity, textTotalValue, textValue});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCaluculate, buttonConfirm, buttonMainMenu});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(radioButtonDisperseFunds)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCashDispersal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioButtonAcceptDeposit)
                    .addComponent(textCashDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radioButtonSell)
                .addGap(18, 18, 18)
                .addComponent(radioButtonBuy)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTransactionQuantity)
                    .addComponent(textQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValue)
                    .addComponent(textValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCommissionRate)
                    .addComponent(textCommissionRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalValue)
                    .addComponent(textTotalValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(buttonCaluculate)
                .addGap(18, 18, 18)
                .addComponent(buttonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonMainMenu)
                .addGap(27, 27, 27))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textCommissionRate, textQuantity});

        getContentPane().add(jPanel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainMenuActionPerformed
        cl.show(homeContainer, "Main Menu");
    }//GEN-LAST:event_buttonMainMenuActionPerformed

    private void buttonLookUpPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLookUpPriceActionPerformed
        textMarketPrice.setText(getQuote());
    }//GEN-LAST:event_buttonLookUpPriceActionPerformed

    private void textCommissionRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCommissionRateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCommissionRateActionPerformed

    private void textLastNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textLastNameMouseClicked
        textLastName.setText("");
        textLastName.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_textLastNameMouseClicked

    private void textFirstNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFirstNameMouseClicked
        textFirstName.setText("");
        textFirstName.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameMouseClicked

    private void textCustomerIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCustomerIDMouseClicked
        textCustomerID.setText("");
        textCustomerID.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_textCustomerIDMouseClicked

    private void textStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textStockMouseClicked
        textStock.setText("");
        textStock.setForeground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_textStockMouseClicked

    private void textQuantityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textQuantityMouseClicked
        textQuantity.setText("");
        textQuantity.setForeground(Color.black);  // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityMouseClicked

    private void textLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textLastNameFocusGained
        textLastName.setText("");
        textLastName.setForeground(Color.black);
    }//GEN-LAST:event_textLastNameFocusGained

    private void textFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFirstNameFocusGained
        textFirstName.setText("");
        textFirstName.setForeground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameFocusGained

    private void textCustomerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textCustomerIDFocusGained
        textCustomerID.setText("");
        textCustomerID.setForeground(Color.black);      // TODO add your handling code here:
    }//GEN-LAST:event_textCustomerIDFocusGained

    private void textStockFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textStockFocusGained
        textStock.setText("");
        textStock.setForeground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_textStockFocusGained

    private void textQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textQuantityFocusGained
        textQuantity.setText("");
        textQuantity.setForeground(Color.black);   // TODO add your handling code here:
    }//GEN-LAST:event_textQuantityFocusGained

    private void buttonCaluculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCaluculateActionPerformed
        boolean isStatusLabelSet = false;
        //setConfirmEnabled(true);
        refreshStatusLabel();
        if (radioButtonDisperseFunds.isSelected()) {
            labelStatus.setVisible(true);
            labelStatus.setText("New Cash Balance will be: " + (Double.parseDouble(textCash.getText()) - Double.parseDouble(textCashDispersal.getText())));
            //setConfirmEnabled(true);
            System.out.println("test ");
        }
        if (radioButtonAcceptDeposit.isSelected()) {
            labelStatus.setVisible(true);
            labelStatus.setText("New Cash Balance will be: " + (Double.parseDouble(textCash.getText()) + Double.parseDouble(textCashDispersal.getText())));
            //setConfirmEnabled(true);
        }
        if (radioButtonSell.isSelected()) {
            labelStatus.setVisible(true);
            if (Double.parseDouble(textQuantity.getText()) > Double.parseDouble(textStockHeld.getText())) {
                labelStatus.setText("Not Enough Stock on Hand to Sell");
                textValue.setText("");
                textTotalValue.setText("");
                isStatusLabelSet = true;
            } else {
                labelStatus.setVisible(true);
                textValue.setText(moneyFormat.format(calculateValue()));
                textTotalValue.setText(moneyFormat.format(calculateTotalSellValue()));
                labelStatus.setText("New Cash Balance will be: " + (Double.parseDouble(textCash.getText()) - calculateTotalSellValue()));
                //setConfirmEnabled(true);
            }
        }
        if (radioButtonBuy.isSelected()) {
            labelStatus.setVisible(true);
            textValue.setText(moneyFormat.format(calculateValue()));
            textTotalValue.setText(moneyFormat.format(calculateTotalBuyValue()));
            labelStatus.setText("New Cash Balance will be: " + (Double.parseDouble(textCash.getText()) + calculateTotalBuyValue()));
            // setConfirmEnabled(true);
        } else {
            if (!isStatusLabelSet) {
                labelStatus.setVisible(true);
                labelStatus.setText("Please Select a Transaction Button");
            }
        }

    }//GEN-LAST:event_buttonCaluculateActionPerformed

    private void radioButtonDisperseFundsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonDisperseFundsActionPerformed
        textValue.setText("");
        textTotalValue.setText("");
        labelTotalValue.setText("Total Value");
        refreshStatusLabel();
    }//GEN-LAST:event_radioButtonDisperseFundsActionPerformed

    private void radioButtonAcceptDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAcceptDepositActionPerformed
        textValue.setText("");
        textTotalValue.setText("");
        labelTotalValue.setText("Total Value");
        refreshStatusLabel();
    }//GEN-LAST:event_radioButtonAcceptDepositActionPerformed

    private void radioButtonSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonSellActionPerformed
        textValue.setText("");
        textTotalValue.setText("");
        labelTotalValue.setText("Total Gain");
        refreshStatusLabel();
    }//GEN-LAST:event_radioButtonSellActionPerformed

    private void radioButtonBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonBuyActionPerformed
        textValue.setText("");
        textTotalValue.setText("");
        labelTotalValue.setText("Total Cost");
        refreshStatusLabel();
    }//GEN-LAST:event_radioButtonBuyActionPerformed

    private void buttonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirmActionPerformed
        if (radioButtonDisperseFunds.isSelected()) {
            testMoney = testMoney - Double.parseDouble(textCashDispersal.getText());
            setBalance();
        }
        if (radioButtonAcceptDeposit.isSelected()) {
            testMoney = testMoney + Double.parseDouble(textCashDeposit.getText());
            setBalance();
        }
        if (radioButtonSell.isSelected()) {
            testMoney = testMoney + calculateTotalSellValue();
            setBalance();
        }
        if (radioButtonBuy.isSelected()) {
            testMoney = testMoney - calculateTotalBuyValue();
            setBalance();
        } else {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_buttonConfirmActionPerformed

    private void textStockInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textStockInputMethodTextChanged
        // setConfirmEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_textStockInputMethodTextChanged

    private void textCommissionRateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textCommissionRateInputMethodTextChanged
        // setConfirmEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_textCommissionRateInputMethodTextChanged

    private void textLastNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textLastNameInputMethodTextChanged
        //  setConfirmEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_textLastNameInputMethodTextChanged

    private void textFirstNameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textFirstNameInputMethodTextChanged
        // setConfirmEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_textFirstNameInputMethodTextChanged

    private void textCustomerIDInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_textCustomerIDInputMethodTextChanged
        //setConfirmEnabled(false); // TODO add your handling code here:
    }//GEN-LAST:event_textCustomerIDInputMethodTextChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCaluculate;
    private javax.swing.JButton buttonConfirm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLookUpPrice;
    private javax.swing.JButton buttonMainMenu;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelAverageBasis;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelCity;
    private javax.swing.JLabel labelCommissionRate;
    private javax.swing.JLabel labelCustomerID;
    private javax.swing.JLabel labelCustomerInfo;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JLabel labelMarketPrice;
    private javax.swing.JLabel labelOneYearHistory;
    private javax.swing.JLabel labelPhone;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel labelStockHeld;
    private javax.swing.JLabel labelStreet;
    private javax.swing.JLabel labelTotalValue;
    private javax.swing.JLabel labelTransactionQuantity;
    private javax.swing.JLabel labelValue;
    private javax.swing.JLabel labelZip;
    private javax.swing.JRadioButton radioButtonAcceptDeposit;
    private javax.swing.JRadioButton radioButtonBuy;
    private javax.swing.JRadioButton radioButtonDisperseFunds;
    private javax.swing.JRadioButton radioButtonSell;
    private javax.swing.JTextArea textAreaOneYearHistory;
    private javax.swing.JTextField textAverageBasis;
    private javax.swing.JTextField textCash;
    private javax.swing.JTextField textCashDeposit;
    private javax.swing.JTextField textCashDispersal;
    private javax.swing.JTextField textCity;
    private javax.swing.JTextField textCommissionRate;
    private javax.swing.JTextField textCustomerID;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textMarketPrice;
    private javax.swing.JTextField textPhone;
    private javax.swing.JTextField textQuantity;
    private javax.swing.JTextField textState;
    private javax.swing.JTextField textStock;
    private javax.swing.JTextField textStockHeld;
    private javax.swing.JTextField textStreet;
    private javax.swing.JTextField textTotalValue;
    private javax.swing.JTextField textValue;
    private javax.swing.JTextField textZip;
    // End of variables declaration//GEN-END:variables

}
